apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bubbleblog
  name: bubbleblog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bubbleblog
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bubbleblog
    spec:
      containers:
      - image: bubble-blog
        name: bubbleblog
        imagePullPolicy: Never
        ports:
        - containerPort: 42069
---
apiVersion: v1
kind: Service
metadata:
  name: bubbleblog-service
spec:
  selector:
    app: bubbleblog
  ports:
    - protocol: TCP
      port: 443
      targetPort: 42069
  type: ClusterIP
